### ISSUE TITLE
Noob alert

### ISSUE THREAD

**Issue by QuadDepo** [ChaoticConundrum/pok3r_re_firmware#10]
Hey i was wondering if someone could tell me the stept build it on OS sierra.

I donwloade cmake with brew, but the command make all doesnt seem to do anything 

`➜  pok3r_re_firmware (master) ✗ make clean
make: *** No rule to make target clean'.  Stop.`

**Comment by theyy29** [comment]
Are you just running `make` in the project directory? CMake works a little differently. First, make a directory outside the project directory, then, call `cmake` from that directory with the project directory as an argument. Then run `make`.

e.g.
```
# starting from project directory
cd ..
mkdir pok3r_re_firmware-build
cd pok3r_re_firmware-build
cmake ../pok3r_re_firmware
make
```
