### ISSUE TITLE
Feature Request - include the Vortex ViBE

### ISSUE THREAD

**Issue by pard68** [ChaoticConundrum/pok3r_re_firmware#15]
Based upon the user manual for the ViBE, I suspect that it uses the same base as the pok3r, as the manual references the pok3r manual for a number of things (like programming). Be stoked to get this supported, I want to program some stuff into the keyboard but currently cannot due limitations in the stock programming method.

**Comment by ChaoticConundrum** [comment]
Do you have the USB VID/PID of the ViBE? This should be added to the `devices` map in `main.cpp`, and it should be able to talk to the keyboard after that. Try a `pok3rtool list`.
